import cc.squirreljme.plugin.general.CollateResourceJarsTask
import cc.squirreljme.plugin.multivm.*
import cc.squirreljme.plugin.multivm.ident.SourceTargetClassifier
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

import java.nio.file.Files
import java.nio.file.Paths
import java.nio.file.StandardCopyOption
import java.nio.file.StandardOpenOption
import java.util.zip.ZipEntry
import java.util.zip.ZipFile
import java.util.zip.ZipInputStream
import java.util.zip.ZipOutputStream

plugins
{
	id "application"
	id "java"
}

apply plugin: "com.github.johnrengelman.shadow"

description = "Standalone SquirrelJME virtual machine on Java."
mainClassName = "cc.squirreljme.vm.standalone.main.Main"

dependencies {
	implementation project(":emulators:springcoat-vm")
	implementation project(":emulators:nanocoat-vm")
	
	// Debugger tool for quick usage
	implementation project(":tools:squirreljme-debugger")
}

java {
	// Use a fixed version of the JVM
	compileJava
	{
		sourceCompatibility = JavaVersion.VERSION_1_7
		targetCompatibility = JavaVersion.VERSION_1_8
		
		// Use the default bootstrap classpath
		options.bootstrapClasspath = null
		
	}
	
	// Maximize debugging
	compileJava.options.debug = true
	compileJava.options.debugOptions.setDebugLevel("source,lines,vars")
	
	// Copy settings
	compileTestJava.options.debug = compileJava.options.debug
	compileTestJava.options.debugOptions = compileJava.options.debugOptions
}

// Mapper for Jar names on files to straight file names
static Iterable<java.nio.file.Path> mapBaseNameP(Iterable<Path> input) {
	List<java.nio.file.Path> result = new ArrayList<>()
	
	input.forEach({path -> result.add(path.getFileName())})
	
	return result
}

static String flatClasspath(Project project) {
	return VMHelpers.classpathAsString(mapBaseNameP(VMHelpers
		.runClassPath(project, new SourceTargetClassifier(
			SourceSet.MAIN_SOURCE_SET_NAME,
			VMType.SPRINGCOAT, BangletVariant.NONE,
			ClutterLevel.RELEASE)) as List<Path>))
}

String MERGED_PREFIX = "SQUIRRELJME.SQC"
String MERGED_PREFIX_DEBUG = "SQUIRRELJME-DEBUG.SQC"

/*tasks.register("collateResourceJars",
	CollateResourceJarsTask.class,
	processResources, ClutterLevel.RELEASE, MERGED_PREFIX)
tasks.register("collateResourceJarsDebug",
	CollateResourceJarsTask.class,
	processResources, ClutterLevel.DEBUG, MERGED_PREFIX_DEBUG)*/

TaskProvider<Task> romRelease = rootProject.tasks.named("romSpringCoatRelease")
TaskProvider<Task> romDebug = rootProject.tasks.named("romSpringCoatDebug")

// Jar Configuration
jar {
	dependsOn processResources, romRelease, romDebug
	mustRunAfter romRelease, romDebug
	
	// We need to set specific manifest properties
	manifest {
		attributes \
			"X-SquirrelJME-BuildVersion": project.provider({ -> 
					VMHelpers.buildVersion(project)
				}),
			"X-SquirrelJME-Standalone-Main-Class":
				"javax.microedition.midlet.__MainHandler__",
			"X-SquirrelJME-Standalone-Parameter":
				"cc.squirreljme.runtime.launcher.ui.MidletMain",
			"X-SquirrelJME-Standalone-Classpath": project.provider({ ->
					return flatClasspath(project(":modules:system-app-launcher"))
				}),
			"X-SquirrelJME-Standalone-Library": project.provider({ ->
					return VMHelpers.classpathAsString(
						mapBaseNameP(VMHelpers.fullSuiteLibraries(
							rootProject.tasks.getByName("fullSpringCoatRelease"))
							as Iterable<Path>))
				}),
			"X-SquirrelJME-Standalone-Internal-Jar-Root": project.provider({ ->
				"/" + MERGED_PREFIX + "/"}),
			"X-SquirrelJME-Standalone-Internal-Debug-Jar-Root": project.provider({ ->
				"/" + MERGED_PREFIX_DEBUG + "/"})
	}
}

def finalizeShadowJar = tasks.register("finalizeShadowJar", {
	group = "squirreljme"
	description = "Finalizes the result of shadowJar."
	
	/*inputs.file(project.provider { -> shadowJar.outputs.files.singleFile})
	outputs.file(project.provider { -> shadowJar.outputs.files.singleFile})*/
	
	outputs.upToDateWhen { Task __task ->
		// If missing, this is not up to date
		java.nio.file.Path srcPath = shadowJar.outputs.files.singleFile.toPath()
		if (!Files.exists(srcPath)) {
			return false
		}
		
		// Must have the standalone entry, if it does we do not have to touch
		// it
		try (ZipFile zip = new ZipFile(srcPath.toFile())) {
			return zip.getEntry("SQUIRRELJME-STANDALONE.MF") != null
		}
	}
	
	doLast {
		java.nio.file.Path srcPath = shadowJar.outputs.files.singleFile.toPath()
		java.nio.file.Path tmpPath = Files.createTempFile("final", ".jar")
		
		boolean wroteSquirrel = false
		try (ZipOutputStream dst = new ZipOutputStream(
				Files.newOutputStream(tmpPath, StandardOpenOption.WRITE,
					StandardOpenOption.TRUNCATE_EXISTING,
					StandardOpenOption.CREATE));
			ZipInputStream src = new ZipInputStream(
				Files.newInputStream(srcPath, StandardOpenOption.READ))) {
			for (;;) {
				ZipEntry entry = src.getNextEntry()
				if (entry == null) {
					break
				}
				
				// Skip directories
				if (entry.isDirectory()) {
					continue
				}
				
				// Do not write entry twice.
				if (wroteSquirrel && entry.name == "SQUIRRELJME-STANDALONE.MF") {
					continue
				}
				
				// Read all input bytes
				byte[] data = VMHelpers.readAll(src)
				
				// Write output
				dst.putNextEntry(entry)
				dst.write(data)
				dst.closeEntry()
				
				// If this is the manifest, duplicate it
				if (entry.name == "META-INF/MANIFEST.MF") {
					dst.putNextEntry(new ZipEntry("SQUIRRELJME-STANDALONE.MF"))
					dst.write(data)
					dst.closeEntry()

					wroteSquirrel = true
				}
			}
			
			// Finalize
			dst.finish()
			dst.flush()
			dst.close()
		}
		
		Files.move(tmpPath, srcPath, StandardCopyOption.REPLACE_EXISTING)
	}
})

// Configuration for ShadowJar
shadowJar {
	dependsOn romRelease, romDebug
	mustRunAfter romRelease, romDebug
	finalizedBy finalizeShadowJar
	
	// Always SquirrelJME
	archiveBaseName.set("squirreljme-standalone")
	
	// Allow the resultant archive to be replaced
	destinationDirectory.fileProvider(project.provider({ ->
		String alt = System.getProperty("squirreljme.standalone.path")

		if (alt != null && !alt.isEmpty()) {
			return Paths.get(alt).toAbsolutePath().normalize()
				.getParent().toFile()
		} else {
			return project.buildDir.toPath().resolve("libs").toFile()
		}
	}) as Provider<File>)
	
	archiveFileName.set(project.provider({ ->
		String alt = System.getProperty("squirreljme.standalone.path")

		if (alt != null && !alt.isEmpty()) {
			return Paths.get(alt).toAbsolutePath().normalize()
				.getFileName().toString()
		} else {
			return String.format("squirreljme-standalone-%s-%s.jar",
				rootProject.version.toString(),
				(String)rootProject.squirreljmeSystemDash)
		}
	}) as Provider<String>)
	
	// Always merge service files, otherwise multiple VMs will just not work
	mergeServiceFiles()
	
	// Inherit all files
	duplicatesStrategy = DuplicatesStrategy.INHERIT
	
	// Include the SpringCoat ROMs
	from zipTree(romRelease.get().outputs.files.singleFile).getAsFileTree()
	from zipTree(romDebug.get().outputs.files.singleFile).getAsFileTree()
	
	// Exclude IntelliJ Annotations, they are not needed
	exclude "org/jetbrains/annotations/*.class"
	exclude "org/intellij/lang/annotations/*.class"
	
	// Exclude Lombok documentation, it confuses people
	exclude "AUTHORS"
	exclude "LICENSE"
	exclude "README.md"
	exclude "changelog.txt"
	exclude "latestchanges.html"
	exclude "release-timestamp.txt"
	
	dependencies {
		// Exclude IntelliJ Annotations, they are not needed
		exclude(dependency("org.jetbrains:annotations-java5:.*"))
	}
}

/**
 * Fills the execution specification.
 * 
 * @param __exec The specification to fill.
 * @param __emulator The emulator to use.
 * @param __isCluttered Is this cluttered?
 * @param __isDebug Is this debugging?
 * @since 2024/06/25
 */
void __fillSpec(JavaExec __exec, VMType __emulator, boolean __isCluttered,
	boolean __isDebug) {
	// These are always the same
	__exec.classpath(project.providers.provider {
		tasks.named("shadowJar").get().getOutputs().getFiles()})
	__exec.mainClass = "cc.squirreljme.vm.standalone.main.Main"
	
	// Build arguments to use
	List<String> args = new ArrayList<>()
	
	// Which emulator is used?
	args += ("-Xemulator:" + __emulator.vmName(VMNameFormat.LOWERCASE))
	
	// Cluttered?
	if (__isCluttered) {
		args += "-Xclutter:debug"
	}
	
	// Debugging?
	if (__isDebug) {
		args += "-Xdebug"
	}
	
	// Use these args
	__exec.args = args
}

// Shadow run tasks for the various emulator choices
[false, true].each { isDebug ->
	[false, true].each { isCluttered ->
		VMType.values().each { vmType ->
			tasks.register("run" + vmType.vmName(VMNameFormat.PROPER_NOUN) +
					(isDebug ? "Debug" : "") +
					(isCluttered ? "Cluttered" : ""),
				JavaExec) { sub ->
				sub.dependsOn tasks.named("shadowJar")
	
				sub.description = "Runs the standalone VM via " +
					"${vmType.properName}" +
					(isDebug ? " with debugging" : "") +
					(isCluttered ? " with cluttering" : "") + "."
				sub.group = "squirreljme"
				
				// Use simplified filler
				__fillSpec(sub, vmType, isCluttered, isDebug)
			}
		}
	}
}
