/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_squirreljme_jvm_mle_ObjectShelf */

#ifndef _Included_cc_squirreljme_jvm_mle_ObjectShelf
#define _Included_cc_squirreljme_jvm_mle_ObjectShelf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_squirreljme_jvm_mle_ObjectShelf
 * Method:    arrayLength
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_mle_ObjectShelf_arrayLength
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cc_squirreljme_jvm_mle_ObjectShelf
 * Method:    arrayNew
 * Signature: (Lcc/squirreljme/jvm/mle/brackets/TypeBracket;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cc_squirreljme_jvm_mle_ObjectShelf_arrayNew
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
