/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_squirreljme_jvm_mle_UIFormShelf */

#ifndef _Included_cc_squirreljme_jvm_mle_UIFormShelf
#define _Included_cc_squirreljme_jvm_mle_UIFormShelf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_squirreljme_jvm_mle_UIFormShelf
 * Method:    displays
 * Signature: ()[Lcc/squirreljme/jvm/mle/brackets/UIDisplayBracket;
 */
JNIEXPORT jobjectArray JNICALL Java_cc_squirreljme_jvm_mle_UIFormShelf_displays
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_mle_UIFormShelf
 * Method:    displayCurrent
 * Signature: (Lcc/squirreljme/jvm/mle/brackets/UIDisplayBracket;)Lcc/squirreljme/jvm/mle/brackets/UIFormBracket;
 */
JNIEXPORT jobject JNICALL Java_cc_squirreljme_jvm_mle_UIFormShelf_displayCurrent
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cc_squirreljme_jvm_mle_UIFormShelf
 * Method:    displayShow
 * Signature: (Lcc/squirreljme/jvm/mle/brackets/UIDisplayBracket;Lcc/squirreljme/jvm/mle/brackets/UIFormBracket;)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_mle_UIFormShelf_displayShow
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cc_squirreljme_jvm_mle_UIFormShelf
 * Method:    equals
 * Signature: (Lcc/squirreljme/jvm/mle/brackets/UIDisplayBracket;Lcc/squirreljme/jvm/mle/brackets/UIDisplayBracket;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_squirreljme_jvm_mle_UIFormShelf_equals__Lcc_squirreljme_jvm_mle_brackets_UIDisplayBracket_2Lcc_squirreljme_jvm_mle_brackets_UIDisplayBracket_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cc_squirreljme_jvm_mle_UIFormShelf
 * Method:    equals
 * Signature: (Lcc/squirreljme/jvm/mle/brackets/UIFormBracket;Lcc/squirreljme/jvm/mle/brackets/UIFormBracket;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_squirreljme_jvm_mle_UIFormShelf_equals__Lcc_squirreljme_jvm_mle_brackets_UIFormBracket_2Lcc_squirreljme_jvm_mle_brackets_UIFormBracket_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cc_squirreljme_jvm_mle_UIFormShelf
 * Method:    equals
 * Signature: (Lcc/squirreljme/jvm/mle/brackets/UIItemBracket;Lcc/squirreljme/jvm/mle/brackets/UIItemBracket;)Z
 */
JNIEXPORT jboolean JNICALL Java_cc_squirreljme_jvm_mle_UIFormShelf_equals__Lcc_squirreljme_jvm_mle_brackets_UIItemBracket_2Lcc_squirreljme_jvm_mle_brackets_UIItemBracket_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     cc_squirreljme_jvm_mle_UIFormShelf
 * Method:    formDelete
 * Signature: (Lcc/squirreljme/jvm/mle/brackets/UIFormBracket;)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_mle_UIFormShelf_formDelete
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cc_squirreljme_jvm_mle_UIFormShelf
 * Method:    formNew
 * Signature: ()Lcc/squirreljme/jvm/mle/brackets/UIFormBracket;
 */
JNIEXPORT jobject JNICALL Java_cc_squirreljme_jvm_mle_UIFormShelf_formNew
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_mle_UIFormShelf
 * Method:    metric
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_mle_UIFormShelf_metric
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
