/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_squirreljme_jvm_mle_RuntimeShelf */

#ifndef _Included_cc_squirreljme_jvm_mle_RuntimeShelf
#define _Included_cc_squirreljme_jvm_mle_RuntimeShelf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_squirreljme_jvm_mle_RuntimeShelf
 * Method:    encoding
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_mle_RuntimeShelf_encoding
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_mle_RuntimeShelf
 * Method:    lineEnding
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_mle_RuntimeShelf_lineEnding
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_mle_RuntimeShelf
 * Method:    locale
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_mle_RuntimeShelf_locale
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
