/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_squirreljme_jvm_mle_TerminalShelf */

#ifndef _Included_cc_squirreljme_jvm_mle_TerminalShelf
#define _Included_cc_squirreljme_jvm_mle_TerminalShelf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_squirreljme_jvm_mle_TerminalShelf
 * Method:    flush
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_mle_TerminalShelf_flush
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_mle_TerminalShelf
 * Method:    write
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_mle_TerminalShelf_write__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_mle_TerminalShelf
 * Method:    write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_mle_TerminalShelf_write__I_3BII
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
