/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cc_squirreljme_jvm_Assembly */

#ifndef _Included_cc_squirreljme_jvm_Assembly
#define _Included_cc_squirreljme_jvm_Assembly
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    arrayLength
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_arrayLength
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    atomicCompareGetAndSet
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_atomicCompareGetAndSet
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    atomicDecrementAndGet
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_atomicDecrementAndGet
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    atomicIncrement
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_atomicIncrement
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    breakpoint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_breakpoint
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    classInfoOfBoolean
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_classInfoOfBoolean
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    classInfoOfByte
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_classInfoOfByte
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    classInfoOfCharacter
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_classInfoOfCharacter
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    classInfoOfDouble
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_classInfoOfDouble
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    classInfoOfFloat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_classInfoOfFloat
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    classInfoOfInteger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_classInfoOfInteger
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    classInfoOfLong
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_classInfoOfLong
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    classInfoOfShort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_classInfoOfShort
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    doublePack
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_cc_squirreljme_jvm_Assembly_doublePack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    doubleToRawLongBits
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_doubleToRawLongBits
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    exceptionHandle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_exceptionHandle
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    floatToRawIntBits
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_floatToRawIntBits
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    intBitsToFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_cc_squirreljme_jvm_Assembly_intBitsToFloat
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invoke
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_invoke__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invoke
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_invoke__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invoke
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_invoke__III
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invoke
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_invoke__IIII
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invoke
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_invoke__IIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invoke
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_invoke__IIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invoke
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_invoke__IIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invoke
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_invoke__IIIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invoke
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_invoke__IIIIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeV
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_invokeV__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeV
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_invokeV__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeV
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_invokeV__III
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeV
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_invokeV__IIII
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeV
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_invokeV__IIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeV
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_invokeV__IIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeV
 * Signature: (IIIIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_invokeV__IIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeV
 * Signature: (IIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_invokeV__IIIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeV
 * Signature: (IIIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_invokeV__IIIIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeVL
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_invokeVL__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeVL
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_invokeVL__III
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeVL
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_invokeVL__IIII
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeVL
 * Signature: (IIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_invokeVL__IIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeVL
 * Signature: (IIIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_invokeVL__IIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeVL
 * Signature: (IIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_invokeVL__IIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeVL
 * Signature: (IIIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_invokeVL__IIIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeVL
 * Signature: (IIIIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_invokeVL__IIIIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    invokeVL
 * Signature: (IIIIIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_invokeVL__IIIIIIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    loadPool
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_loadPool
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    longBitsToDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_cc_squirreljme_jvm_Assembly_longBitsToDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    longPack
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_longPack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    longUnpackHigh
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_longUnpackHigh
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    longUnpackLow
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_longUnpackLow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    memReadByte
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_memReadByte
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    memReadInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_memReadInt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    memReadJavaInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_memReadJavaInt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    memReadJavaShort
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_memReadJavaShort
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    memReadShort
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_memReadShort
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    memWriteByte
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_memWriteByte
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    memWriteInt
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_memWriteInt
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    memWriteJavaInt
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_memWriteJavaInt
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    memWriteJavaShort
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_memWriteJavaShort
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    memWriteShort
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_memWriteShort
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    objectToPointer
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_objectToPointer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    objectToPointerRefQueue
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_objectToPointerRefQueue
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    pointerToObject
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_cc_squirreljme_jvm_Assembly_pointerToObject
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    pointerToClassInfo
 * Signature: (I)Lcc/squirreljme/jvm/ClassInfo;
 */
JNIEXPORT jobject JNICALL Java_cc_squirreljme_jvm_Assembly_pointerToClassInfo
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    refCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_refCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    refUncount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_refUncount
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    returnFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_returnFrame__
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    returnFrame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_returnFrame__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    returnFrame
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_returnFrame__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    specialGetExceptionRegister
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_specialGetExceptionRegister
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    specialGetPoolRegister
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_specialGetPoolRegister
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    specialGetReturnRegister
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_specialGetReturnRegister
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    specialGetReturnHighRegister
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_specialGetReturnHighRegister
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    specialGetReturnLowRegister
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_specialGetReturnLowRegister
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    specialGetStaticFieldRegister
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_specialGetStaticFieldRegister
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    specialGetThreadRegister
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_specialGetThreadRegister
  (JNIEnv *, jclass);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    specialSetExceptionRegister
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_specialSetExceptionRegister
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    specialSetPoolRegister
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_specialSetPoolRegister
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    specialSetStaticFieldRegister
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_specialSetStaticFieldRegister
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    specialSetThreadRegister
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_specialSetThreadRegister
  (JNIEnv *, jclass, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCall
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCall__S
  (JNIEnv *, jclass, jshort);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCall
 * Signature: (SI)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCall__SI
  (JNIEnv *, jclass, jshort, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCall
 * Signature: (SII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCall__SII
  (JNIEnv *, jclass, jshort, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCall
 * Signature: (SIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCall__SIII
  (JNIEnv *, jclass, jshort, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCall
 * Signature: (SIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCall__SIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCall
 * Signature: (SIIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCall__SIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCall
 * Signature: (SIIIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCall__SIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCall
 * Signature: (SIIIIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCall__SIIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCall
 * Signature: (SIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCall__SIIIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallP
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallP__S
  (JNIEnv *, jclass, jshort);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallP
 * Signature: (SI)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallP__SI
  (JNIEnv *, jclass, jshort, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallP
 * Signature: (SII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallP__SII
  (JNIEnv *, jclass, jshort, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallP
 * Signature: (SIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallP__SIII
  (JNIEnv *, jclass, jshort, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallP
 * Signature: (SIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallP__SIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallP
 * Signature: (SIIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallP__SIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallP
 * Signature: (SIIIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallP__SIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallP
 * Signature: (SIIIIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallP__SIIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallP
 * Signature: (SIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallP__SIIIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPV
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPV__S
  (JNIEnv *, jclass, jshort);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPV
 * Signature: (SI)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPV__SI
  (JNIEnv *, jclass, jshort, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPV
 * Signature: (SII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPV__SII
  (JNIEnv *, jclass, jshort, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPV
 * Signature: (SIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPV__SIII
  (JNIEnv *, jclass, jshort, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPV
 * Signature: (SIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPV__SIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPV
 * Signature: (SIIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPV__SIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPV
 * Signature: (SIIIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPV__SIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPV
 * Signature: (SIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPV__SIIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPV
 * Signature: (SIIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPV__SIIIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPVL
 * Signature: (S)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPVL__S
  (JNIEnv *, jclass, jshort);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPVL
 * Signature: (SI)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPVL__SI
  (JNIEnv *, jclass, jshort, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPVL
 * Signature: (SII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPVL__SII
  (JNIEnv *, jclass, jshort, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPVL
 * Signature: (SIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPVL__SIII
  (JNIEnv *, jclass, jshort, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPVL
 * Signature: (SIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPVL__SIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPVL
 * Signature: (SIIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPVL__SIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPVL
 * Signature: (SIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPVL__SIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPVL
 * Signature: (SIIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPVL__SIIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallPVL
 * Signature: (SIIIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallPVL__SIIIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallV
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallV__S
  (JNIEnv *, jclass, jshort);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallV
 * Signature: (SI)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallV__SI
  (JNIEnv *, jclass, jshort, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallV
 * Signature: (SII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallV__SII
  (JNIEnv *, jclass, jshort, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallV
 * Signature: (SIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallV__SIII
  (JNIEnv *, jclass, jshort, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallV
 * Signature: (SIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallV__SIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallV
 * Signature: (SIIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallV__SIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallV
 * Signature: (SIIIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallV__SIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallV
 * Signature: (SIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallV__SIIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallV
 * Signature: (SIIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallV__SIIIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallVL
 * Signature: (S)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallVL__S
  (JNIEnv *, jclass, jshort);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallVL
 * Signature: (SI)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallVL__SI
  (JNIEnv *, jclass, jshort, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallVL
 * Signature: (SII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallVL__SII
  (JNIEnv *, jclass, jshort, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallVL
 * Signature: (SIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallVL__SIII
  (JNIEnv *, jclass, jshort, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallVL
 * Signature: (SIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallVL__SIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallVL
 * Signature: (SIIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallVL__SIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallVL
 * Signature: (SIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallVL__SIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallVL
 * Signature: (SIIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallVL__SIIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cc_squirreljme_jvm_Assembly
 * Method:    sysCallVL
 * Signature: (SIIIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_cc_squirreljme_jvm_Assembly_sysCallVL__SIIIIIIII
  (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
