# GitHub Bot to keep updates for versions:

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    rebase-strategy: "disabled"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "monthly"
      day: friday
  - package-ecosystem: "docker"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "monthly"
      day: friday
