plugins {
	id "java-library"
}

// Java 9 and up!
sourceCompatibility = JavaVersion.VERSION_1_9
targetCompatibility = JavaVersion.VERSION_1_9

description = "JavaDoc Doclet to Doclet Compatibility Wrapper"

dependencies {
	implementation project(":modules:cldc-compact")
	api project(":tools:squirreljme-javadoc-classic")
}
