plugins {
	id "java"
	id "application"
}

apply plugin: "com.github.johnrengelman.shadow"

description = "Extracts ZIP files."
mainClassName = "cc.squirreljme.unzip.Main"

// The Java versions this works with
sourceCompatibility = JavaVersion.VERSION_1_7
targetCompatibility = JavaVersion.VERSION_1_8

dependencies {
	implementation project(":modules:vendor-api-squirreljme-zip")
	implementation project(":modules:vendor-api-squirreljme-io")
}
