# ---------------------------------------------------------------------------
# Multi-Phasic Applications: SquirrelJME
#     Copyright (C) Stephanie Gawroriski <xer@multiphasicapps.net>
# ---------------------------------------------------------------------------
# SquirrelJME is under the GNU General Public License v3, or later.
# See license.mkd for licensing and copyright information.
# ---------------------------------------------------------------------------
# DESCRIPTION: OpenWatcom C++ Makefile for DOS
# $ wmake -f makefile.dos

sjme_dos.exe:	sjmerc.c sys_stdc.c
		wcl -fe=$@ -l=dos -dSQUIRRELJME_PORT_STDC -d__DOS__ sjmerc.c sys_stdc.c
