# ---------------------------------------------------------------------------
# SquirrelJME
#     Copyright (C) Stephanie Gawroriski <xer@multiphasicapps.net>
# ---------------------------------------------------------------------------
# SquirrelJME is under the Mozilla Public License Version 2.0.
# See license.mkd for licensing and copyright information.
# ---------------------------------------------------------------------------
# DESCRIPTION: Platform flags

# Is this RetroArch? Any kind of RetroArch build?
if(RETROARCH OR ENV{RETROARCH} OR
	LIBRETRO_STATIC OR ENV{LIBRETRO_STATIC} OR
	LIBRETRO_SUFFIX OR ENV{LIBRETRO_SUFFIX} OR
	ENV{LIBRETRO})
	set(SQUIRRELJME_IS_LIBRETRO YES)
else()
	set(SQUIRRELJME_IS_LIBRETRO NO)
endif()

# Mac OS X Desktop?
if("${SQUIRRELJME_SYSTEM}" STREQUAL "macosx" AND
	NOT SQUIRRELJME_IS_LIBRETRO)
	set(SQUIRRELJME_IS_APPLE_DESKTOP YES)
else()
	set(SQUIRRELJME_IS_APPLE_DESKTOP NO)
endif()

# Can we be GNUStep?
if(NOT SQUIRRELJME_IS_APPLE_DESKTOP AND
	NOT SQUIRRELJME_IS_LIBRETRO AND
	(SQUIRRELJME_IS_UNIX OR SQUIRRELJME_IS_WINDOWS))
	# Is there gnu-step?
	find_program(GNUSTEP_EXE_PATH gnustep-config)

	# If there is, then GNUStep is available
	if(GNUSTEP_EXE_PATH)
		set(SQUIRRELJME_IS_GNUSTEP_DESKTOP YES)
	else()
		set(SQUIRRELJME_IS_GNUSTEP_DESKTOP NO)
	endif()
else()
	set(SQUIRRELJME_IS_GNUSTEP_DESKTOP NO)
endif()

# Output results of what is above
message(STATUS "Cross Compiled? ${SQUIRRELJME_IS_CROSS_COMPILE}")
message(STATUS "Is UNIX? ${SQUIRRELJME_IS_UNIX}")
message(STATUS "Is Windows? ${SQUIRRELJME_IS_WINDOWS}")
message(STATUS "Is Apple? ${SQUIRRELJME_IS_APPLE_DESKTOP}")
message(STATUS "Is GNUStep? ${SQUIRRELJME_IS_GNUSTEP_DESKTOP}")
message(STATUS "Is libretro? ${SQUIRRELJME_IS_LIBRETRO}")

# Options
## Dynamic libraries?
if(SQUIRRELJME_IS_BARE_METAL OR
	"${SQUIRRELJME_SYSTEM}" STREQUAL "amiga" OR
	"${SQUIRRELJME_SYSTEM}" STREQUAL "emscripten" OR
	"${SQUIRRELJME_SYSTEM}" STREQUAL "palmos" OR
	LIBRETRO_STATIC OR ENV{LIBRETRO_STATIC})
	set(SQUIRRELJME_ENABLE_DYLIB_DEFAULT OFF)
else()
	set(SQUIRRELJME_ENABLE_DYLIB_DEFAULT ON)
endif()

## Netscape JRI Interface?
if((SQUIRRELJME_IS_RETRO OR SQUIRRELJME_ENABLE_DYLIB_DEFAULT) AND
	NOT "${SQUIRRELJME_SYSTEM}" STREQUAL "wine")
	set(SQUIRRELJME_ENABLE_FRONTEND_JRI_DEFAULT ON)
else()
	set(SQUIRRELJME_ENABLE_FRONTEND_JRI_DEFAULT OFF)
endif()

## LibRetro?
if(SQUIRRELJME_IS_RETRO OR SQUIRRELJME_IS_BARE_METAL OR
	"${SQUIRRELJME_SYSTEM}" STREQUAL "wine")
	set(SQUIRRELJME_ENABLE_FRONTEND_LIBRETRO_DEFAULT OFF)
else()
	set(SQUIRRELJME_ENABLE_FRONTEND_LIBRETRO_DEFAULT ON)
endif()

## Testing?
if(SQUIRRELJME_IS_CROSS_COMPILE OR
	${CMAKE_VERSION} VERSION_LESS_EQUAL "3.12")
	set(SQUIRRELJME_ENABLE_TESTING_DEFAULT OFF)
else()
	set(SQUIRRELJME_ENABLE_TESTING_DEFAULT ON)
endif()

## FPIC?
if("${SQUIRRELJME_SYSTEM}" STREQUAL "playstation2" OR
	"${SQUIRRELJME_SYSTEM}" STREQUAL "psp" OR
	"${SQUIRRELJME_SYSTEM}" STREQUAL "sdcc" OR
	"${SQUIRRELJME_SYSTEM}" STREQUAL "vita" OR
	"${SQUIRRELJME_SYSTEM}" STREQUAL "windows")
	set(SQUIRRELJME_ENABLE_FPIC_DEFAULT OFF)
else()
	set(SQUIRRELJME_ENABLE_FPIC_DEFAULT ON)
endif()

# Option flags which are available
option(SQUIRRELJME_ENABLE_DYLIB "Enable Dynamic Libraries"
	${SQUIRRELJME_ENABLE_DYLIB_DEFAULT})
option(SQUIRRELJME_ENABLE_FPIC "Enable FPIC"
	${SQUIRRELJME_ENABLE_FPIC_DEFAULT})
option(SQUIRRELJME_ENABLE_FRONTEND_JRI "Enable Front End: JRI"
	${SQUIRRELJME_ENABLE_FRONTEND_JRI_DEFAULT})
option(SQUIRRELJME_ENABLE_FRONTEND_LIBRETRO "Enable Front End: LibRetro"
	${SQUIRRELJME_ENABLE_FRONTEND_LIBRETRO_DEFAULT})
option(SQUIRRELJME_ENABLE_TESTING "Enable Host System Tests"
	${SQUIRRELJME_ENABLE_TESTING_DEFAULT})

# Verbose these
message(STATUS "ENABLE_DYLIB: ${SQUIRRELJME_ENABLE_DYLIB}")
message(STATUS "ENABLE_FPIC: ${SQUIRRELJME_ENABLE_FPIC}")
message(STATUS "ENABLE_FRONTEND_JRI: ${SQUIRRELJME_ENABLE_FRONTEND_JRI}")
message(STATUS "ENABLE_FRONTEND_LIBRETRO: ${SQUIRRELJME_ENABLE_FRONTEND_LIBRETRO}")
message(STATUS "ENABLE_TESTING: ${SQUIRRELJME_ENABLE_TESTING}")
