/* -*- Mode: C; indent-tabs-mode: t; tab-width: 4 -*-
// ---------------------------------------------------------------------------
// Multi-Phasic Applications: SquirrelJME
//     Copyright (C) Stephanie Gawroriski <xer@multiphasicapps.net>
// ---------------------------------------------------------------------------
// SquirrelJME is under the GNU General Public License v3+, or later.
// See license.mkd for licensing and copyright information.
// --------------------------------------------------------------------------
// THIS FILE IS AUTOMATICALLY GENERATED FOR THE BUILT-IN ROM, DO NOT EDIT OR
// OTHERWISE MODIFY THIS FILE. IF A BUILT-IN IS NOT DESIRED THIS MAY BE
// SAFELY DELETED! */

#include "builtin.h"
