import cc.squirreljme.plugin.multivm.VMHelpers
import cc.squirreljme.plugin.util.MIMEFileDecoder

import java.nio.file.Files
import java.nio.file.StandardOpenOption

plugins {
	id "java"
	id "application"
}

apply plugin: "com.github.johnrengelman.shadow"

description = "Performs bundling and otherwise from CI/CD."
mainClassName = "cc.squirreljme.cicd.Main"

dependencies {
	implementation project(":modules:vendor-api-squirreljme-io")
	
	// Lombok for simpler getters/setters
	implementation 'org.projectlombok:lombok:1.18.36'
	annotationProcessor 'org.projectlombok:lombok:1.18.36'
	
	// Jackson, for JSON APIs
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr353:2.17.2'
	implementation 'org.glassfish:javax.json:1.1'
}

TaskProvider<Task> internals = tasks.register('internals') {
	group = "squirreljme"
	description = "Builds and collects all of the internal tasks."
	
	dependsOn(
		rootProject.tasks.named("romNanoCoatDebug"),
		rootProject.tasks.named("romNanoCoatRelease"),
		rootProject.tasks.named("romTestNanoCoatDebug"),
		project(":emulators:standalone").tasks.named("shadowJar"))
	mustRunAfter(tasks.named("clean"))
	
	doLast {
		java.nio.file.Path inBase = rootProject.projectDir.toPath()
			.resolve("assets").resolve("mascot")
		java.nio.file.Path outBase = rootProject.projectDir.toPath()
			.resolve("build").resolve("install4j").resolve("in")
		
		// Make sure the output exists
		Files.createDirectories(outBase)
		
		// Decode files
		for (String name : Arrays.asList("head_8x8.png",
			"head_16x16.png",
			"head_24x24.png",
			"head_32x32.png",
			"head_48x48.png",
			"head_64x64.png",
			"head_128x128.png")) {
			try (MIMEFileDecoder mime = new MIMEFileDecoder(Files.newInputStream(
				inBase.resolve(name + ".__mime"), StandardOpenOption.READ))) {
				Files.write(outBase.resolve(name), VMHelpers.readAll(mime),
					StandardOpenOption.CREATE, StandardOpenOption.WRITE,
					StandardOpenOption.TRUNCATE_EXISTING)
			}
		}
	}
}

CommandLineArgumentProvider argProvider = ({ ->
	// Pass in SquirrelJME version
	List<String> args = new ArrayList<>()
	args.add(squirreljmeVersion)
	args.add(rootProject.projectDir.toPath().toAbsolutePath()
		.normalize().toString())
	
	// Pass all task dependencies
	for (Object item : internals.get().dependsOn) {
		if (item instanceof Provider) {
			item = ((Provider)item).get()
		}
		
		if (item instanceof Task) {
			Task sub = (Task)item
			
			for (File file : sub.outputs.files.asFileTree.files) {
				args.add(String.format("%s=%s",
					sub.name,
					file.toPath().toAbsolutePath().toString()))
			}
		}
	}
	
	return args
} as CommandLineArgumentProvider)

runShadow {
	dependsOn(internals)
	mustRunAfter(tasks.named("clean"))
	
	workingDir(rootProject.projectDir)
	
	getArgumentProviders().add(argProvider)
}

run {
	dependsOn(internals)
	mustRunAfter(tasks.named("clean"))
	
	workingDir(rootProject.projectDir)
	
	getArgumentProviders().add(argProvider)
}

