// -*- Mode: Java; indent-tabs-mode: t; tab-width: 4 -*-
// ---------------------------------------------------------------------------
// Multi-Phasic Applications: SquirrelJME
//     Copyright (C) Steven Gawroriski <steven@multiphasicapps.net>
//     Copyright (C) Multi-Phasic Applications <multiphasicapps.net>
// ---------------------------------------------------------------------------
// SquirrelJME is under the GNU General Public License v3+, or later.
// See license.mkd for licensing and copyright information.
// ---------------------------------------------------------------------------

package net.multiphasicapps.squirreljme.jit;

import net.multiphasicapps.squirreljme.executable.ExecutableClass;

/**
 * This class is used to build executables generated by the JIT which may
 * later be serialized to the disk, combined to create the kernel, or may be
 * directly executed by the kernel after compilation.
 *
 * @since 2017/02/04
 */
public class JITExecutableBuilder
{
	/**
	 * Builds the resulting output executable which may be used for execution.
	 *
	 * @return Builds the resulting executable.
	 * @since 2017/02/04
	 */
	public ExecutableClass build()
	{
		throw new Error("TODO");
	}
}

