/* -*- Mode: C; indent-tabs-mode: t; tab-width: 4 -*-
// ---------------------------------------------------------------------------
// SquirrelJME
//     Copyright (C) Stephanie Gawroriski <xer@multiphasicapps.net>
// ---------------------------------------------------------------------------
// SquirrelJME is under the Mozilla Public License Version 2.0.
// See license.mkd for licensing and copyright information.
// -------------------------------------------------------------------------*/

#include "sjme/nvm/task.h"
#include "sjme/nvm/bytecode.h"
#include "sjme/debug.h"

const sjme_nvm_byteCode_func (*sjme_nvm_byteCode_lutTable
	[SJME_NVM_NUM_JAVA_BYTECODES])[SJME_NVM_NUM_JAVA_BYTECODES] =
{
	/* ..0 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* ..1 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* ..2 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* ..3 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* ..4 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* ..5 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* ..6 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* ..7 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* ..8 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* ..9 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .10 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .11 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .12 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .13 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .14 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .15 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .16 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .17 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .18 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .19 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .20 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .21 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .22 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .23 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .24 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .25 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .26 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .27 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .28 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .29 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .30 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .31 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .32 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .33 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .34 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .35 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .36 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .37 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .38 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .39 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .40 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .41 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .42 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .43 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .44 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .45 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .46 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .47 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .48 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .49 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .50 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .51 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .52 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .53 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .54 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .55 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .56 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .57 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .58 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .59 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .60 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .61 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .62 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .63 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .64 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .65 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .66 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .67 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .68 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .69 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .70 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .71 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .72 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .73 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .74 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .75 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .76 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .77 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .78 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .79 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .80 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .81 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .82 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .83 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .84 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .85 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .86 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .87 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .88 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .89 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .90 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .91 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .92 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .93 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .94 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .95 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .96 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .97 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .98 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* .99 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 100 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 101 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 102 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 103 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 104 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 105 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 106 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 107 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 108 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 109 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 110 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 111 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 112 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 113 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 114 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 115 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 116 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 117 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 118 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 119 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 120 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 121 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 122 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 123 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 124 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 125 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 126 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 127 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 128 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 129 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 130 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 131 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 132 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 133 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 134 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 135 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 136 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 137 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 138 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 139 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 140 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 141 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 142 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 143 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 144 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 145 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 146 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 147 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 148 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 149 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 150 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 151 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 152 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 153 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 154 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 155 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 156 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 157 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 158 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 159 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 160 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 161 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 162 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 163 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 164 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 165 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 166 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 167 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 168 */ NULL,
	/* 169 */ NULL,
	/* 170 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 171 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 172 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 173 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 174 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 175 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 176 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 177 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 178 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 179 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 180 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 181 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 182 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 183 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 184 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 185 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 186 */ NULL,
	/* 187 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 188 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 189 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 190 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 191 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 192 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 193 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 194 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 195 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 196 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 197 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 198 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 199 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 200 */ &sjme_nvm_byteCode_slowNarrowFunctions,
	/* 201 */ NULL,
	/* 202 */ NULL,
	/* 203 */ NULL,
	/* 204 */ NULL,
	/* 205 */ NULL,
	/* 206 */ NULL,
	/* 207 */ NULL,
	/* 208 */ NULL,
	/* 209 */ NULL,
	/* 210 */ NULL,
	/* 211 */ NULL,
	/* 212 */ NULL,
	/* 213 */ NULL,
	/* 214 */ NULL,
	/* 215 */ NULL,
	/* 216 */ NULL,
	/* 217 */ NULL,
	/* 218 */ NULL,
	/* 219 */ NULL,
	/* 220 */ NULL,
	/* 221 */ NULL,
	/* 222 */ NULL,
	/* 223 */ NULL,
	/* 224 */ NULL,
	/* 225 */ NULL,
	/* 226 */ NULL,
	/* 227 */ NULL,
	/* 228 */ NULL,
	/* 229 */ NULL,
	/* 230 */ NULL,
	/* 231 */ NULL,
	/* 232 */ NULL,
	/* 233 */ NULL,
	/* 234 */ NULL,
	/* 235 */ NULL,
	/* 236 */ NULL,
	/* 237 */ NULL,
	/* 238 */ NULL,
	/* 239 */ NULL,
	/* 240 */ NULL,
	/* 241 */ NULL,
	/* 242 */ NULL,
	/* 243 */ NULL,
	/* 244 */ NULL,
	/* 245 */ NULL,
	/* 246 */ NULL,
	/* 247 */ NULL,
	/* 248 */ NULL,
	/* 249 */ NULL,
	/* 250 */ NULL,
	/* 251 */ NULL,
	/* 252 */ NULL,
	/* 253 */ NULL,
	/* 254 */ NULL,
	/* 255 */ NULL,
};

sjme_errorCode sjme_nvm_byteCode_illegalInstruction(
	sjme_attrInNotNull sjme_nvm_frame inFrame,
	sjme_attrInRange(0, 256) sjme_byteCode id,
	sjme_attrInNotNull sjme_byteCode* relRawCode,
	sjme_attrInNotNull sjme_nvm_byteCode_pcNew* pcNew)
{
	if (inFrame == NULL || relRawCode == NULL || pcNew == NULL)
		return SJME_ERROR_NULL_ARGUMENTS;

	sjme_message("ILLEGAL INSTRUCTION %d at 0x%x",
		id, relRawCode - inFrame->inCode->rawCode);
	sjme_nvm_task_stackTrace(inFrame->inThread);
	sjme_message_hexDump(inFrame->inCode->rawCode,
		inFrame->inCode->rawCodeLen);
	return SJME_ERROR_INVALID_INSTRUCTION;
}

sjme_errorCode sjme_nvm_byteCode_notImplemented(
	sjme_attrInNotNull sjme_nvm_frame inFrame,
	sjme_attrInRange(0, 256) sjme_byteCode id,
	sjme_attrInNotNull sjme_byteCode* relRawCode,
	sjme_attrInNotNull sjme_nvm_byteCode_pcNew* pcNew)
{
	if (inFrame == NULL || relRawCode == NULL || pcNew == NULL)
		return SJME_ERROR_NULL_ARGUMENTS;

	sjme_nvm_task_stackTrace(inFrame->inThread);
	sjme_todo("Impl? %d", relRawCode[0]);
	return sjme_error_notImplemented(relRawCode[0]);
}
