import cc.squirreljme.plugin.swm.JavaMEConfiguration
import cc.squirreljme.plugin.swm.JavaMEMidletType

// Setup plugins
plugins
{
	id "java"
}

version = "1.8.$squirreljmeVMVersion"
description = "This is the standard JavaME 8 Connection " +
	"Limited Device Configuration which contains the core classes used " +
	"by Java ME."

squirreljme
{
	javaDocErrorCode = "ZZ"
	swmType = JavaMEMidletType.API
	swmName = "Connected Limited Device Configuration (Compact)"
	swmVendor = "Stephanie Gawroriski"
	definedConfigurations += new JavaMEConfiguration("CLDC-1.8-Compact")
	definedConfigurations += new JavaMEConfiguration("CLDC-1.1.1")
	definedConfigurations += new JavaMEConfiguration("CLDC-1.1")
	definedConfigurations += new JavaMEConfiguration("CLDC-1.0")
	tags += "required"
	tags += "lite"
	noEmitConfiguration = true
		
	// The test method that takes 255 arguments completely breaks ProGuard
	// so disable optimizations for it
	proGuardOptionsTest += ["-keep", "class",
		"lang.bytecode.TestInvoke255"]
	proGuardOptionsTest += ["-keepnames", "class",
		"lang.bytecode.TestInvoke255"]
	proGuardOptionsTest += ["-keep,includecode",
		"class", "lang.bytecode.TestInvoke255", "{",
			"<fields>", ";",
			"<methods>", ";",
		"}"
	]
	
	// This is considered a boot loader for SummerCoat
	isBootLoader = true
	bootLoaderMainClass = "cc.squirreljme.jvm.summercoat.Bootstrap"
}

java
{
	// No classes are available for this project
	compileJava.options.bootstrapClasspath = project.objects.fileCollection()
}

dependencies
{
	// For IDE related information
	api "org.jetbrains:annotations:26.1.0"
	
//	// Static contract checking, note that this version is Java 8 compatible
//	api "org.checkerframework:checker-qual:3.55.1"
}
