import cc.squirreljme.plugin.tasks.MimeDecodeResourcesTask

plugins {
	id "java"
	id "application"
}

apply plugin: "com.github.johnrengelman.shadow"

description = "SquirrelJME Interactive Debugger."
mainClassName = "cc.squirreljme.debugger.Main"

// The Java versions this works with
sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

tasks.register("mimeDecode", MimeDecodeResourcesTask.class,
	"main",
	tasks.named("processResources").get(),
	tasks.named("clean").get())

processResources.dependsOn("mimeDecode")
jar.dependsOn("mimeDecode")

dependencies {
	implementation project(":emulators:emulator-base")
	implementation project(":modules:debug-jdwp")
	implementation project(":modules:tango-icon-theme")
	implementation project(":modules:common-vm")
	implementation project(":modules:vendor-api-oracle-json")
	implementation project(":modules:system-app-launcher")
	
	// Lombok for simpler getters/setters
	implementation 'org.projectlombok:lombok:1.18.36'
	annotationProcessor 'org.projectlombok:lombok:1.18.36'
}
