plugins {
	id "java"
}

apply plugin: "com.github.johnrengelman.shadow"

repositories {
	mavenLocal()
	mavenCentral()
}

dependencies {
	shadow localGroovy()
	shadow gradleApi()
}

/*task relocateShadowJar(type: ConfigureShadowRelocation) {
	target = tasks.shadowJar
}

shadowJar {
	dependsOn relocateShadowJar
}*/
