/* -*- Mode: C++; indent-tabs-mode: t; tab-width: 4 -*- */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_squirreljme_emulator_NativeBinding */

#ifndef _Included_cc_squirreljme_emulator_NativeBinding
#define _Included_cc_squirreljme_emulator_NativeBinding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_squirreljme_emulator_NativeBinding
 * Method:    __bindMethods
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_squirreljme_emulator_NativeBinding__1_1bindMethods
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
