import cc.squirreljme.plugin.swm.JavaMEMidletType

description = "Keitai Wiki Community Music Implementation"
version = rootProject.version

squirreljme
{
	javaDocErrorCode = "KW"
	swmType = JavaMEMidletType.API
	swmName = "Keitai Wiki Community Music Implementation"
	swmVendor = "Keitai Wiki Community"
	alwaysOptimize = true
}

dependencies
{
	api project(":modules:cldc-compact")
	api project(":modules:vendor-api-squirreljme-io")
	api project(":modules:media-api")
	
	// TODO: Remove
	api project(":modules:cldc")
}
